/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ContactUsRouteImport } from './routes/contactUs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CreateAccountRouteImport } from './routes/CreateAccount'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardDashboardRouteImport } from './routes/dashboard/dashboard'
import { Route as DashboardDashboardIndexRouteImport } from './routes/dashboard/dashboard/index'
import { Route as DashboardDashboardVendorsRouteImport } from './routes/dashboard/dashboard/vendors'
import { Route as DashboardDashboardVehiclesRouteImport } from './routes/dashboard/dashboard/vehicles'
import { Route as DashboardDashboardSettingsRouteImport } from './routes/dashboard/dashboard/settings'
import { Route as DashboardDashboardServicesRouteImport } from './routes/dashboard/dashboard/services'
import { Route as DashboardDashboardReviewsRouteImport } from './routes/dashboard/dashboard/reviews'
import { Route as DashboardDashboardProfileRouteImport } from './routes/dashboard/dashboard/profile'
import { Route as DashboardDashboardPaymentsRouteImport } from './routes/dashboard/dashboard/payments'
import { Route as DashboardDashboardCustomersRouteImport } from './routes/dashboard/dashboard/customers'
import { Route as DashboardDashboardBookingsRouteImport } from './routes/dashboard/dashboard/bookings'
import { Route as DashboardDashboardMyServicesRouteImport } from './routes/dashboard/dashboard/MyServices'
import { Route as DashboardDashboardMyBookingsRouteImport } from './routes/dashboard/dashboard/MyBookings'
import { Route as DashboardDashboardAllReviewsRouteImport } from './routes/dashboard/dashboard/AllReviews'
import { Route as DashboardDashboardAllBookingsRouteImport } from './routes/dashboard/dashboard/AllBookings'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contactUs',
  path: '/contactUs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAccountRoute = CreateAccountRouteImport.update({
  id: '/CreateAccount',
  path: '/CreateAccount',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard/dashboard',
  path: '/dashboard/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardIndexRoute = DashboardDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDashboardRoute,
} as any)
const DashboardDashboardVendorsRoute =
  DashboardDashboardVendorsRouteImport.update({
    id: '/vendors',
    path: '/vendors',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardVehiclesRoute =
  DashboardDashboardVehiclesRouteImport.update({
    id: '/vehicles',
    path: '/vehicles',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardSettingsRoute =
  DashboardDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardServicesRoute =
  DashboardDashboardServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardReviewsRoute =
  DashboardDashboardReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardProfileRoute =
  DashboardDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardPaymentsRoute =
  DashboardDashboardPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardCustomersRoute =
  DashboardDashboardCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardBookingsRoute =
  DashboardDashboardBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardMyServicesRoute =
  DashboardDashboardMyServicesRouteImport.update({
    id: '/MyServices',
    path: '/MyServices',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardMyBookingsRoute =
  DashboardDashboardMyBookingsRouteImport.update({
    id: '/MyBookings',
    path: '/MyBookings',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardAllReviewsRoute =
  DashboardDashboardAllReviewsRouteImport.update({
    id: '/AllReviews',
    path: '/AllReviews',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardAllBookingsRoute =
  DashboardDashboardAllBookingsRouteImport.update({
    id: '/AllBookings',
    path: '/AllBookings',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/CreateAccount': typeof CreateAccountRoute
  '/about': typeof AboutRoute
  '/contactUs': typeof ContactUsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/signin': typeof SigninRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/dashboard/dashboard': typeof DashboardDashboardRouteWithChildren
  '/dashboard/dashboard/AllBookings': typeof DashboardDashboardAllBookingsRoute
  '/dashboard/dashboard/AllReviews': typeof DashboardDashboardAllReviewsRoute
  '/dashboard/dashboard/MyBookings': typeof DashboardDashboardMyBookingsRoute
  '/dashboard/dashboard/MyServices': typeof DashboardDashboardMyServicesRoute
  '/dashboard/dashboard/bookings': typeof DashboardDashboardBookingsRoute
  '/dashboard/dashboard/customers': typeof DashboardDashboardCustomersRoute
  '/dashboard/dashboard/payments': typeof DashboardDashboardPaymentsRoute
  '/dashboard/dashboard/profile': typeof DashboardDashboardProfileRoute
  '/dashboard/dashboard/reviews': typeof DashboardDashboardReviewsRoute
  '/dashboard/dashboard/services': typeof DashboardDashboardServicesRoute
  '/dashboard/dashboard/settings': typeof DashboardDashboardSettingsRoute
  '/dashboard/dashboard/vehicles': typeof DashboardDashboardVehiclesRoute
  '/dashboard/dashboard/vendors': typeof DashboardDashboardVendorsRoute
  '/dashboard/dashboard/': typeof DashboardDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/CreateAccount': typeof CreateAccountRoute
  '/about': typeof AboutRoute
  '/contactUs': typeof ContactUsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/signin': typeof SigninRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/dashboard/dashboard/AllBookings': typeof DashboardDashboardAllBookingsRoute
  '/dashboard/dashboard/AllReviews': typeof DashboardDashboardAllReviewsRoute
  '/dashboard/dashboard/MyBookings': typeof DashboardDashboardMyBookingsRoute
  '/dashboard/dashboard/MyServices': typeof DashboardDashboardMyServicesRoute
  '/dashboard/dashboard/bookings': typeof DashboardDashboardBookingsRoute
  '/dashboard/dashboard/customers': typeof DashboardDashboardCustomersRoute
  '/dashboard/dashboard/payments': typeof DashboardDashboardPaymentsRoute
  '/dashboard/dashboard/profile': typeof DashboardDashboardProfileRoute
  '/dashboard/dashboard/reviews': typeof DashboardDashboardReviewsRoute
  '/dashboard/dashboard/services': typeof DashboardDashboardServicesRoute
  '/dashboard/dashboard/settings': typeof DashboardDashboardSettingsRoute
  '/dashboard/dashboard/vehicles': typeof DashboardDashboardVehiclesRoute
  '/dashboard/dashboard/vendors': typeof DashboardDashboardVendorsRoute
  '/dashboard/dashboard': typeof DashboardDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/CreateAccount': typeof CreateAccountRoute
  '/about': typeof AboutRoute
  '/contactUs': typeof ContactUsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/signin': typeof SigninRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/dashboard/dashboard': typeof DashboardDashboardRouteWithChildren
  '/dashboard/dashboard/AllBookings': typeof DashboardDashboardAllBookingsRoute
  '/dashboard/dashboard/AllReviews': typeof DashboardDashboardAllReviewsRoute
  '/dashboard/dashboard/MyBookings': typeof DashboardDashboardMyBookingsRoute
  '/dashboard/dashboard/MyServices': typeof DashboardDashboardMyServicesRoute
  '/dashboard/dashboard/bookings': typeof DashboardDashboardBookingsRoute
  '/dashboard/dashboard/customers': typeof DashboardDashboardCustomersRoute
  '/dashboard/dashboard/payments': typeof DashboardDashboardPaymentsRoute
  '/dashboard/dashboard/profile': typeof DashboardDashboardProfileRoute
  '/dashboard/dashboard/reviews': typeof DashboardDashboardReviewsRoute
  '/dashboard/dashboard/services': typeof DashboardDashboardServicesRoute
  '/dashboard/dashboard/settings': typeof DashboardDashboardSettingsRoute
  '/dashboard/dashboard/vehicles': typeof DashboardDashboardVehiclesRoute
  '/dashboard/dashboard/vendors': typeof DashboardDashboardVendorsRoute
  '/dashboard/dashboard/': typeof DashboardDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/CreateAccount'
    | '/about'
    | '/contactUs'
    | '/privacy-policy'
    | '/register'
    | '/signin'
    | '/terms-of-service'
    | '/dashboard/dashboard'
    | '/dashboard/dashboard/AllBookings'
    | '/dashboard/dashboard/AllReviews'
    | '/dashboard/dashboard/MyBookings'
    | '/dashboard/dashboard/MyServices'
    | '/dashboard/dashboard/bookings'
    | '/dashboard/dashboard/customers'
    | '/dashboard/dashboard/payments'
    | '/dashboard/dashboard/profile'
    | '/dashboard/dashboard/reviews'
    | '/dashboard/dashboard/services'
    | '/dashboard/dashboard/settings'
    | '/dashboard/dashboard/vehicles'
    | '/dashboard/dashboard/vendors'
    | '/dashboard/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/CreateAccount'
    | '/about'
    | '/contactUs'
    | '/privacy-policy'
    | '/register'
    | '/signin'
    | '/terms-of-service'
    | '/dashboard/dashboard/AllBookings'
    | '/dashboard/dashboard/AllReviews'
    | '/dashboard/dashboard/MyBookings'
    | '/dashboard/dashboard/MyServices'
    | '/dashboard/dashboard/bookings'
    | '/dashboard/dashboard/customers'
    | '/dashboard/dashboard/payments'
    | '/dashboard/dashboard/profile'
    | '/dashboard/dashboard/reviews'
    | '/dashboard/dashboard/services'
    | '/dashboard/dashboard/settings'
    | '/dashboard/dashboard/vehicles'
    | '/dashboard/dashboard/vendors'
    | '/dashboard/dashboard'
  id:
    | '__root__'
    | '/'
    | '/CreateAccount'
    | '/about'
    | '/contactUs'
    | '/privacy-policy'
    | '/register'
    | '/signin'
    | '/terms-of-service'
    | '/dashboard/dashboard'
    | '/dashboard/dashboard/AllBookings'
    | '/dashboard/dashboard/AllReviews'
    | '/dashboard/dashboard/MyBookings'
    | '/dashboard/dashboard/MyServices'
    | '/dashboard/dashboard/bookings'
    | '/dashboard/dashboard/customers'
    | '/dashboard/dashboard/payments'
    | '/dashboard/dashboard/profile'
    | '/dashboard/dashboard/reviews'
    | '/dashboard/dashboard/services'
    | '/dashboard/dashboard/settings'
    | '/dashboard/dashboard/vehicles'
    | '/dashboard/dashboard/vendors'
    | '/dashboard/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateAccountRoute: typeof CreateAccountRoute
  AboutRoute: typeof AboutRoute
  ContactUsRoute: typeof ContactUsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RegisterRoute: typeof RegisterRoute
  SigninRoute: typeof SigninRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  DashboardDashboardRoute: typeof DashboardDashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactUs': {
      id: '/contactUs'
      path: '/contactUs'
      fullPath: '/contactUs'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/CreateAccount': {
      id: '/CreateAccount'
      path: '/CreateAccount'
      fullPath: '/CreateAccount'
      preLoaderRoute: typeof CreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/dashboard': {
      id: '/dashboard/dashboard'
      path: '/dashboard/dashboard'
      fullPath: '/dashboard/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/dashboard/': {
      id: '/dashboard/dashboard/'
      path: '/'
      fullPath: '/dashboard/dashboard/'
      preLoaderRoute: typeof DashboardDashboardIndexRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/dashboard/dashboard/vendors': {
      id: '/dashboard/dashboard/vendors'
      path: '/vendors'
      fullPath: '/dashboard/dashboard/vendors'
      preLoaderRoute: typeof DashboardDashboardVendorsRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/dashboard/dashboard/vehicles': {
      id: '/dashboard/dashboard/vehicles'
      path: '/vehicles'
      fullPath: '/dashboard/dashboard/vehicles'
      preLoaderRoute: typeof DashboardDashboardVehiclesRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/dashboard/dashboard/settings': {
      id: '/dashboard/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/dashboard/settings'
      preLoaderRoute: typeof DashboardDashboardSettingsRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/dashboard/dashboard/services': {
      id: '/dashboard/dashboard/services'
      path: '/services'
      fullPath: '/dashboard/dashboard/services'
      preLoaderRoute: typeof DashboardDashboardServicesRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/dashboard/dashboard/reviews': {
      id: '/dashboard/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/dashboard/reviews'
      preLoaderRoute: typeof DashboardDashboardReviewsRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/dashboard/dashboard/profile': {
      id: '/dashboard/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/dashboard/profile'
      preLoaderRoute: typeof DashboardDashboardProfileRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/dashboard/dashboard/payments': {
      id: '/dashboard/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/dashboard/payments'
      preLoaderRoute: typeof DashboardDashboardPaymentsRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/dashboard/dashboard/customers': {
      id: '/dashboard/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/dashboard/customers'
      preLoaderRoute: typeof DashboardDashboardCustomersRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/dashboard/dashboard/bookings': {
      id: '/dashboard/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/dashboard/bookings'
      preLoaderRoute: typeof DashboardDashboardBookingsRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/dashboard/dashboard/MyServices': {
      id: '/dashboard/dashboard/MyServices'
      path: '/MyServices'
      fullPath: '/dashboard/dashboard/MyServices'
      preLoaderRoute: typeof DashboardDashboardMyServicesRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/dashboard/dashboard/MyBookings': {
      id: '/dashboard/dashboard/MyBookings'
      path: '/MyBookings'
      fullPath: '/dashboard/dashboard/MyBookings'
      preLoaderRoute: typeof DashboardDashboardMyBookingsRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/dashboard/dashboard/AllReviews': {
      id: '/dashboard/dashboard/AllReviews'
      path: '/AllReviews'
      fullPath: '/dashboard/dashboard/AllReviews'
      preLoaderRoute: typeof DashboardDashboardAllReviewsRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/dashboard/dashboard/AllBookings': {
      id: '/dashboard/dashboard/AllBookings'
      path: '/AllBookings'
      fullPath: '/dashboard/dashboard/AllBookings'
      preLoaderRoute: typeof DashboardDashboardAllBookingsRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
  }
}

interface DashboardDashboardRouteChildren {
  DashboardDashboardAllBookingsRoute: typeof DashboardDashboardAllBookingsRoute
  DashboardDashboardAllReviewsRoute: typeof DashboardDashboardAllReviewsRoute
  DashboardDashboardMyBookingsRoute: typeof DashboardDashboardMyBookingsRoute
  DashboardDashboardMyServicesRoute: typeof DashboardDashboardMyServicesRoute
  DashboardDashboardBookingsRoute: typeof DashboardDashboardBookingsRoute
  DashboardDashboardCustomersRoute: typeof DashboardDashboardCustomersRoute
  DashboardDashboardPaymentsRoute: typeof DashboardDashboardPaymentsRoute
  DashboardDashboardProfileRoute: typeof DashboardDashboardProfileRoute
  DashboardDashboardReviewsRoute: typeof DashboardDashboardReviewsRoute
  DashboardDashboardServicesRoute: typeof DashboardDashboardServicesRoute
  DashboardDashboardSettingsRoute: typeof DashboardDashboardSettingsRoute
  DashboardDashboardVehiclesRoute: typeof DashboardDashboardVehiclesRoute
  DashboardDashboardVendorsRoute: typeof DashboardDashboardVendorsRoute
  DashboardDashboardIndexRoute: typeof DashboardDashboardIndexRoute
}

const DashboardDashboardRouteChildren: DashboardDashboardRouteChildren = {
  DashboardDashboardAllBookingsRoute: DashboardDashboardAllBookingsRoute,
  DashboardDashboardAllReviewsRoute: DashboardDashboardAllReviewsRoute,
  DashboardDashboardMyBookingsRoute: DashboardDashboardMyBookingsRoute,
  DashboardDashboardMyServicesRoute: DashboardDashboardMyServicesRoute,
  DashboardDashboardBookingsRoute: DashboardDashboardBookingsRoute,
  DashboardDashboardCustomersRoute: DashboardDashboardCustomersRoute,
  DashboardDashboardPaymentsRoute: DashboardDashboardPaymentsRoute,
  DashboardDashboardProfileRoute: DashboardDashboardProfileRoute,
  DashboardDashboardReviewsRoute: DashboardDashboardReviewsRoute,
  DashboardDashboardServicesRoute: DashboardDashboardServicesRoute,
  DashboardDashboardSettingsRoute: DashboardDashboardSettingsRoute,
  DashboardDashboardVehiclesRoute: DashboardDashboardVehiclesRoute,
  DashboardDashboardVendorsRoute: DashboardDashboardVendorsRoute,
  DashboardDashboardIndexRoute: DashboardDashboardIndexRoute,
}

const DashboardDashboardRouteWithChildren =
  DashboardDashboardRoute._addFileChildren(DashboardDashboardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateAccountRoute: CreateAccountRoute,
  AboutRoute: AboutRoute,
  ContactUsRoute: ContactUsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RegisterRoute: RegisterRoute,
  SigninRoute: SigninRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  DashboardDashboardRoute: DashboardDashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
